// src/view/Margherita.svelte
<script lang="ts">
  import { IconRowInsertBottom } from "@tabler/icons-svelte";
  import Paper from "./components/Paper.svelte";
  import CalculatorRow from "./components/CalculatorRow.svelte";
  import WillametteMall from "/willamette-mall.mp3?url";
  import { type RowDetails, create as newRow } from "../@types/RowDetails.mts";

  let rows: RowDetails[] = $state([newRow()]);
  let disableDelete = $derived(rows.length === 1);

  function findRowIndex(row: RowDetails) {
    return rows.findIndex((r) => r.id === row.id);
  }
</script>

<div class="h-screen flex bg-no-repeat bg-cover bg-[url(/pizza.webp)]">
  <div class="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>
  <div class="container mx-auto my-4 z-10">
    <div class="flex flex-col items-center gap-5">
      <span class="text-7xl font-lobster text-white text-shadow-lg/80">
        margherita
      </span>
      <div class="w-xl">
        <Paper>
          <div class="flex flex-col gap-2 w-full">
            <div class="flex flex-col gap-2">
              {#each rows as row}
                <CalculatorRow
                  {row}
                  {disableDelete}
                  setPrice={(n) => {
                    const index = findRowIndex(row);
                    rows[index].price = n;
                  }}
                  setSize={(n) => {
                    const index = findRowIndex(row);
                    rows[index].size = n;
                  }}
                  onDelete={() => {
                    const index = findRowIndex(row);
                    rows.splice(index, 1);
                  }}
                />
              {/each}
              <div>
                <button
                  class="btn btn-success w-full"
                  onclick={() => rows.push(newRow())}
                >
                  <IconRowInsertBottom /> Add Row
                </button>
              </div>
            </div>
            <div class="flex flex-col content-center items-center gap-2">
              <audio controls autoPlay loop>
                <source src={WillametteMall} type="audio/mp3" />
              </audio>
              <span class="caption-bottom text-xs">
                Willamette Mall Music is &copy; Capcom 2006
              </span>
            </div>
          </div>
        </Paper>
      </div>
    </div>
  </div>
</div>

// src/view/Margherita.tsx
import * as React from "react";
import { useReducer } from "react";
import { initialState } from "../state/State.mts";
import { reducer } from "../state/reducer.mts";
import WillametteMall from "/willamette-mall.mp3?url";
import { CalculatorRow } from "./components/CalculatorRow";
import { Paper } from "./components/Paper";
import { IconRowInsertBottom } from "@tabler/icons-react";

export function Margherita() {
  const [state, dispatch] = useReducer(reducer, initialState);

  return (
    <div className="h-screen flex bg-no-repeat bg-cover bg-[url(/pizza.webp)]">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>
      <div className="container mx-auto my-4 z-10">
        <div className="flex flex-col items-center gap-5">
          <span className="text-7xl font-lobster text-white text-shadow-lg/80">
            margherita
          </span>
          <div className="w-xl">
            <Paper>
              <div className="flex flex-col gap-2 w-full">
                <div className="flex flex-col gap-2">
                  {state.rows.map((row) => (
                    <CalculatorRow
                      row={row}
                      key={row.id}
                      dispatch={dispatch}
                      disableDelete={state.rows.length === 1}
                      onDelete={() =>
                        dispatch({ action: "remove-row", id: row.id })
                      }
                    />
                  ))}
                  <div>
                    <button
                      className="btn btn-success w-full"
                      onClick={() => dispatch({ action: "add-row" })}
                    >
                      <IconRowInsertBottom /> Add Row
                    </button>
                  </div>
                </div>
                <div className="flex flex-col content-center items-center gap-2">
                  <audio controls autoPlay loop>
                    <source src={WillametteMall} type="audio/mp3" />
                  </audio>
                  <span className="caption-bottom text-xs">
                    Willamette Mall Music is &copy; Capcom 2006
                  </span>
                </div>
              </div>
            </Paper>
          </div>
        </div>
      </div>
    </div>
  );
}
