// src/view/components/CalculatorRow.svelte
<script lang="ts">
  import {
    IconCurrencyDollar,
    IconRulerMeasure2,
    IconCalculator,
    IconRowRemove,
  } from "@tabler/icons-svelte";
  import { formatCurrency } from "../../util/currency.mts";
  import { type RowDetails } from "../../@types/RowDetails.mts";
  import { calculate } from "../../util/calculate.mts";
  import { type UserEnteredNumber } from "../../@types/UserEnteredNumber.mts";

  interface CalculatorRowProps {
    row: RowDetails;
    disableDelete: boolean;
    setSize: (n: UserEnteredNumber) => void;
    setPrice: (n: UserEnteredNumber) => void;
    onDelete: () => void;
  }

  let props: CalculatorRowProps = $props();
  let costEfficiency = $derived(calculate(props.row.price, props.row.size));

  function sanitizeInput(input: string): UserEnteredNumber {
    // Ensure we're only looking at numbers, and at most six of them.
    const onlyDigits = input.replace(/[^\d]/, "").substring(0, 6);
    const attempt = parseInt(onlyDigits);
    if (isNaN(attempt)) {
      return "";
    }
    return attempt;
  }
</script>

<div class="flex gap-2 w-full">
  <label class="input flex-1 bg-slate-50/75">
    <IconCurrencyDollar />
    <input
      type="tel"
      autoComplete="off"
      oninput={(e) => props.setPrice(sanitizeInput(e.currentTarget.value))}
      value={props.row.price}
    />
  </label>
  <label class="input flex-1 bg-slate-50/75">
    <IconRulerMeasure2 />
    <input
      type="tel"
      autoComplete="off"
      oninput={(e) => props.setSize(sanitizeInput(e.currentTarget.value))}
      value={props.row.size}
    />
    <span>in</span>
  </label>
  <label class="input flex-1 bg-slate-50/75">
    <IconCalculator />
    <input
      type="text"
      readOnly
      value={costEfficiency === "" ? "—" : formatCurrency(costEfficiency)}
    />
    <span>/in²</span>
  </label>
  <button
    class="btn btn-error"
    disabled={props.disableDelete}
    onclick={props.onDelete}
  >
    <IconRowRemove />
  </button>
</div>

// src/view/components/CalculatorRow.tsx
import * as React from "react";
import {
  IconCurrencyDollar,
  IconRowRemove,
  IconRulerMeasure2,
  IconCalculator,
} from "@tabler/icons-react";
import { Message } from "../../state/Message.mts";
import { RowDetails } from "../../@types/RowDetails.mts";
import { formatCurrency } from "../../util/currency.mts";
import { calculate } from "../../util/calculate.mts";

interface RowProps {
  row: RowDetails;
  dispatch: React.Dispatch<Message>;
  disableDelete: boolean;
  onDelete: () => void;
}

export function CalculatorRow(props: RowProps) {
  const { row, dispatch } = props;

  const costEfficiency = calculate(row.price, row.size);

  return (
    <div className="flex gap-2 w-full">
      <label className="input flex-1 bg-slate-50/75">
        <IconCurrencyDollar />
        <input
          type="tel"
          autoComplete="off"
          value={row.price}
          onChange={(e) =>
            dispatch({ action: "set-price", id: row.id, value: e.target.value })
          }
        />
      </label>
      <label className="input flex-1 bg-slate-50/75">
        <IconRulerMeasure2 />
        <input
          type="tel"
          autoComplete="off"
          value={row.size}
          onChange={(e) =>
            dispatch({ action: "set-size", id: row.id, value: e.target.value })
          }
        />
        <span>in</span>
      </label>
      <label className="input flex-1 bg-slate-50/75">
        <IconCalculator />
        <input
          type="text"
          readOnly
          value={costEfficiency === "" ? "—" : formatCurrency(costEfficiency)}
        />
        <span>/in²</span>
      </label>
      <button className="btn btn-error" disabled={props.disableDelete}>
        <IconRowRemove onClick={props.onDelete} />
      </button>
    </div>
  );
}
